import AppKit
import SwiftUI
import Security
import CryptoKit

// Credentials never enter UserDefaults or the account metadata file.
protocol CredentialVault {
    func read(_ service: String, _ account: String) throws -> Data?
    func write(_ data: Data, _ service: String, _ account: String) throws
    func remove(_ service: String, _ account: String) throws
}
// Claude Code creates its Keychain items through Apple's signed security tool.
// Use the same client so each ad hoc ccs/mini build does not need its own ACL grant.
struct ClaudeKeychain {
    var run: ([String], Data?) throws -> (Int32, Data) = { arguments, input in
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/security")
        process.arguments = arguments
        let output = Pipe()
        let stdin = Pipe()
        process.standardOutput = output
        // Never put credential data or security's interactive command echo in logs.
        process.standardError = FileHandle.nullDevice
        process.standardInput = input == nil ? FileHandle.nullDevice : stdin.fileHandleForReading
        try process.run()
        if let input {
            try stdin.fileHandleForWriting.write(contentsOf: input)
            try stdin.fileHandleForWriting.close()
        }
        let data = output.fileHandleForReading.readDataToEndOfFile()
        process.waitUntilExit()
        return (process.terminationStatus, data)
    }
    static func handles(_ service: String) -> Bool {
        service == "Claude Code-credentials" || service.hasPrefix("Claude Code-credentials-")
    }
    func check(_ status: Int32) throws {
        guard status != 0 else { return }
        // security exposes the low byte of the OSStatus as its exit status.
        for error in [errSecAuthFailed, errSecUserCanceled, errSecInteractionNotAllowed] {
            if status == (error & 255) { throw AccountError.message(KeychainVault.errorMessage(error)) }
        }
        throw AccountError.message("Claude Code Keychain access failed (security exit \(status)). Unlock the login keychain and try again.")
    }
    func read(_ service: String, _ account: String) throws -> Data? {
        let (status, output) = try run(["find-generic-password", "-s", service, "-a", account, "-w"], nil)
        if status == (errSecItemNotFound & 255) { return nil }
        try check(status)
        var data = output
        if data.last == 10 { data.removeLast() } // security appends one newline.
        // security prints non-ASCII passwords as hex. Claude credentials are JSON,
        // so a plain hex response cannot be confused with the original payload.
        if !data.isEmpty, data.count.isMultiple(of: 2),
           data.allSatisfy({ (48...57).contains($0) || (65...70).contains($0) || (97...102).contains($0) }) {
            let bytes = Array(data)
            func nibble(_ byte: UInt8) -> UInt8 { byte <= 57 ? byte - 48 : (byte | 32) - 87 }
            return Data(stride(from: 0, to: bytes.count, by: 2).map { nibble(bytes[$0]) << 4 | nibble(bytes[$0 + 1]) })
        }
        return data
    }
    static func writeCommand(_ data: Data, _ service: String, _ account: String) -> Data? {
        // These identifiers are generated by ccs; reject interactive command syntax.
        guard [service, account].allSatisfy({ $0.range(of: "^[a-zA-Z0-9 ._-]+$", options: .regularExpression) != nil }) else { return nil }
        let hex = data.map { String(format: "%02x", $0) }.joined()
        let command = Data("add-generic-password -U -s \"\(service)\" -a \"\(account)\" -X \"\(hex)\"\n".utf8)
        // security -i has a fixed input buffer. Larger payloads use the native API
        // rather than truncating the credential or exposing it in process arguments.
        return command.count <= 4000 ? command : nil
    }
    func write(_ command: Data) throws {
        let (status, _) = try run(["-i"], command)
        try check(status)
    }
    func remove(_ service: String, _ account: String) throws {
        let (status, _) = try run(["delete-generic-password", "-s", service, "-a", account], nil)
        if status != (errSecItemNotFound & 255) { try check(status) }
    }
}
struct KeychainVault: CredentialVault {
    func query(_ service: String, _ account: String) -> [String: Any] {
        [kSecClass as String: kSecClassGenericPassword, kSecAttrService as String: service, kSecAttrAccount as String: account]
    }
    func check(_ status: OSStatus) throws {
        guard status != errSecSuccess else { return }
        var signatureStatus = errSecSuccess
        if status == errSecAuthFailed {
            var code: SecCode?
            signatureStatus = SecCodeCopySelf([], &code)
            if signatureStatus == errSecSuccess, let code {
                signatureStatus = SecCodeCheckValidity(code, [], nil)
            }
        }
        throw AccountError.message(Self.errorMessage(status, signatureStatus: signatureStatus))
    }
    static func errorMessage(_ status: OSStatus, signatureStatus: OSStatus = errSecSuccess) -> String {
        if status == errSecAuthFailed && signatureStatus != errSecSuccess {
            return "ccs was updated while running or its signature is invalid. Quit and reopen ccs, then refresh Accounts. If this persists, rebuild after quitting ccs. Saved accounts have not been removed."
        }
        switch status {
        case errSecAuthFailed:
            return "Keychain access was denied. Allow ccs access if macOS asks, then refresh Accounts. If no prompt appears, quit and reopen ccs and check that the login keychain is unlocked in Keychain Access."
        case errSecUserCanceled:
            return "Keychain access was canceled. Refresh Accounts to try again."
        case errSecInteractionNotAllowed:
            return "Keychain interaction is unavailable. Unlock your Mac and the login keychain, then refresh Accounts."
        default:
            let detail = SecCopyErrorMessageString(status, nil) as String? ?? "Unknown error"
            return "Keychain error (\(status)): \(detail)"
        }
    }
    func read(_ service: String, _ account: String) throws -> Data? {
        if ClaudeKeychain.handles(service) { return try ClaudeKeychain().read(service, account) }
        var q = query(service, account); q[kSecReturnData as String] = true; q[kSecMatchLimit as String] = kSecMatchLimitOne
        var result: CFTypeRef?
        let status = SecItemCopyMatching(q as CFDictionary, &result)
        if status == errSecItemNotFound { return nil }
        try check(status)
        return result as? Data
    }
    func write(_ data: Data, _ service: String, _ account: String) throws {
        if ClaudeKeychain.handles(service), let command = ClaudeKeychain.writeCommand(data, service, account) {
            try ClaudeKeychain().write(command)
            return
        }
        let q = query(service, account)
        let status = SecItemUpdate(q as CFDictionary, [kSecValueData as String: data] as CFDictionary)
        if status == errSecItemNotFound {
            var new = q; new[kSecValueData as String] = data
            new[kSecAttrAccessible as String] = kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly
            try check(SecItemAdd(new as CFDictionary, nil))
        } else { try check(status) }
    }
    func remove(_ service: String, _ account: String) throws {
        if ClaudeKeychain.handles(service) { return try ClaudeKeychain().remove(service, account) }
        let status = SecItemDelete(query(service, account) as CFDictionary)
        if status != errSecItemNotFound { try check(status) }
    }
}
enum AccountError: LocalizedError {
    case message(String)
    case rateLimited
    var errorDescription: String? {
        switch self {
        case .message(let message): return message
        case .rateLimited: return "Usage temporarily rate limited (HTTP 429). Try again later."
        }
    }
}
enum AccountProvider: String, Codable, CaseIterable, Identifiable {
    case codex = "Codex", claude = "Claude"
    var id: String { rawValue }
    var command: String { rawValue.lowercased() }
}
struct SavedAccount: Codable, Identifiable {
    var id: String
    var provider: AccountProvider
    var identity: String
    var name: String
}
struct AccountSecret: Codable {
    var credentials: Data
    var profile: Data?
}
struct UsageWindow: Identifiable {
    var label: String
    var used: Double
    var reset: Date?
    var id: String { label }
}
struct AccountUsage {
    var windows: [UsageWindow] = []
    var updated: Date?
    var error: String?
}

enum CodexDesktopLauncher {
    static func arguments(app: URL, home: URL) -> [String] {
        ["--env", "CODEX_HOME=\(home.appendingPathComponent(".codex").path)", app.path]
    }
    static func stop(_ applications: [NSRunningApplication]) throws {
        for application in applications where !application.isTerminated {
            guard application.terminate() else {
                throw AccountError.message("Could not close Codex Desktop. Close it and try switching again.")
            }
        }
        let deadline = Date().addingTimeInterval(20)
        while applications.contains(where: { !$0.isTerminated }) && Date() < deadline {
            Thread.sleep(forTimeInterval: 0.1)
        }
        guard applications.allSatisfy(\.isTerminated) else {
            throw AccountError.message("Codex Desktop is still open. Finish or close its current task, then try switching again.")
        }
    }
    static func launch(app: URL, home: URL) throws {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/open")
        process.arguments = arguments(app: app, home: home)
        process.standardOutput = FileHandle.nullDevice
        process.standardError = FileHandle.nullDevice
        try process.run()
        process.waitUntilExit()
        guard process.terminationStatus == 0 else {
            throw AccountError.message("macOS could not reopen Codex Desktop (open exited \(process.terminationStatus)).")
        }
    }
}

// Claude Desktop keeps its own Electron login, separate from Claude Code's
// Keychain credentials. Keep each Desktop profile intact and select it before
// reopening the app. Moving directories on the same volume is atomic and
// avoids copying browser cookies or token caches into ccs metadata.
struct ClaudeDesktopProfiles {
    let repository: AccountRepository
    var desktop: URL { repository.home.appendingPathComponent("Library/Application Support/Claude") }
    var root: URL { repository.root.appendingPathComponent("claude-desktop") }
    var profiles: URL { root.appendingPathComponent("profiles") }
    var selection: URL { root.appendingPathComponent("selected.json") }

    func desktopUUID() -> String? {
        let config = desktop.appendingPathComponent("config.json")
        guard let data = try? Data(contentsOf: config),
              let object = try? repository.object(data),
              let value = object["lastKnownAccountUuid"] as? String,
              UUID(uuidString: value) != nil else { return nil }
        return value.lowercased()
    }

    func selectedID() -> String? {
        guard let data = try? Data(contentsOf: selection),
              let object = try? repository.object(data),
              let value = object["accountID"] as? String,
              UUID(uuidString: value) != nil else { return nil }
        return value
    }

    func accountUUID(_ account: SavedAccount) -> String? {
        let value = String(account.identity.split(separator: ":", omittingEmptySubsequences: false).first ?? "")
        return UUID(uuidString: value)?.uuidString.lowercased()
    }

    func currentSlot(accounts: [SavedAccount]) -> String? {
        if let uuid = desktopUUID() {
            return accounts.first(where: { $0.provider == .claude && accountUUID($0) == uuid })?.id ?? "unmanaged-\(uuid)"
        }
        return selectedID()
    }

    // Returns whether the selected Desktop profile already has this login.
    @discardableResult func select(_ account: SavedAccount, accounts: [SavedAccount]) throws -> Bool {
        guard account.provider == .claude, UUID(uuidString: account.id) != nil else {
            throw AccountError.message("Invalid Claude account record.")
        }
        guard let targetUUID = accountUUID(account) else {
            throw AccountError.message("This Claude Code account has no Desktop-compatible account ID. Sign in to Claude Code again and reimport it.")
        }
        let files = FileManager.default
        let current = currentSlot(accounts: accounts)
        if current == account.id { return desktopUUID() == targetUUID }
        let target = profiles.appendingPathComponent(account.id, isDirectory: true)
        let outgoing = current.map { profiles.appendingPathComponent($0, isDirectory: true) }
            ?? profiles.appendingPathComponent("unassigned-\(UUID().uuidString)", isDirectory: true)
        let hasDesktop = files.fileExists(atPath: desktop.path)
        let hasTarget = files.fileExists(atPath: target.path)
        if hasDesktop && files.fileExists(atPath: outgoing.path) {
            throw AccountError.message("A saved Claude Desktop profile already occupies this account's slot. No login data was changed.")
        }
        if hasTarget {
            let config = target.appendingPathComponent("config.json")
            if let data = try? Data(contentsOf: config),
               let object = try? repository.object(data),
               let uuid = object["lastKnownAccountUuid"] as? String,
               uuid.lowercased() != targetUUID {
                throw AccountError.message("The saved Claude Desktop login does not match this Claude Code account. No login data was changed.")
            }
        }
        try files.createDirectory(at: profiles, withIntermediateDirectories: true, attributes: [.posixPermissions: 0o700])
        let oldSelection = try? Data(contentsOf: selection)
        var movedOutgoing = false
        var movedTarget = false
        var createdEmpty = false
        do {
            if hasDesktop {
                try files.moveItem(at: desktop, to: outgoing)
                movedOutgoing = true
            }
            if hasTarget {
                try files.moveItem(at: target, to: desktop)
                movedTarget = true
            } else {
                try files.createDirectory(at: desktop, withIntermediateDirectories: false, attributes: [.posixPermissions: 0o700])
                createdEmpty = true
            }
            try repository.secureWrite(repository.encode(["accountID": account.id]), to: selection)
        } catch {
            do {
                if createdEmpty { try files.removeItem(at: desktop) }
                if movedTarget { try files.moveItem(at: desktop, to: target) }
                if movedOutgoing { try files.moveItem(at: outgoing, to: desktop) }
                if let oldSelection { try repository.secureWrite(oldSelection, to: selection) }
                else if files.fileExists(atPath: selection.path) { try files.removeItem(at: selection) }
            } catch {
                throw AccountError.message("Claude Desktop profile switch and rollback failed. Profiles are preserved in \(profiles.path). Close Claude Desktop and inspect them before retrying.")
            }
            throw error
        }
        return hasTarget && desktopUUID() == targetUUID
    }
}

enum ClaudeDesktopLauncher {
    static func stop(_ applications: [NSRunningApplication]) throws {
        for application in applications where !application.isTerminated {
            guard application.terminate() else { throw AccountError.message("Could not close Claude Desktop. Close it and retry.") }
        }
        let deadline = Date().addingTimeInterval(20)
        while applications.contains(where: { !$0.isTerminated }) && Date() < deadline { Thread.sleep(forTimeInterval: 0.1) }
        guard applications.allSatisfy(\.isTerminated) else {
            throw AccountError.message("Claude Desktop is still open. Finish its current work, then retry switching.")
        }
    }
    static func launch(app: URL) throws {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/open")
        process.arguments = [app.path]
        process.standardOutput = FileHandle.nullDevice
        process.standardError = FileHandle.nullDevice
        try process.run()
        process.waitUntilExit()
        guard process.terminationStatus == 0 else {
            throw AccountError.message("macOS could not reopen Claude Desktop (open exited \(process.terminationStatus)).")
        }
    }
}

final class AccountRepository {
    let home: URL
    let root: URL
    let vault: CredentialVault
    let service = "ccs Accounts"
    let legacyService = "SessionSpot Accounts"
    var user: String {
        let name = NSUserName()
        return name.range(of: "^[a-zA-Z0-9._-]+$", options: .regularExpression) != nil ? name : "claude-code-user"
    }
    init(home: URL = FileManager.default.homeDirectoryForCurrentUser, root: URL? = nil, vault: CredentialVault = KeychainVault()) {
        self.home = home
        self.root = root ?? home.appendingPathComponent("Library/Application Support/ccs/accounts")
        self.vault = vault
        if root == nil && !FileManager.default.fileExists(atPath: self.root.path) {
            let legacy = home.appendingPathComponent("Library/Application Support/SessionSpot/accounts")
            if FileManager.default.fileExists(atPath: legacy.path) {
                try? FileManager.default.createDirectory(at: self.root.deletingLastPathComponent(), withIntermediateDirectories: true)
                try? FileManager.default.copyItem(at: legacy, to: self.root)
            }
        }
    }
    func object(_ data: Data) throws -> [String: Any] {
        guard let result = try JSONSerialization.jsonObject(with: data) as? [String: Any] else { throw AccountError.message("Invalid account data.") }
        return result
    }
    func encode(_ object: [String: Any]) throws -> Data { try JSONSerialization.data(withJSONObject: object, options: [.sortedKeys]) }
    func secureWrite(_ data: Data, to url: URL) throws {
        try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true, attributes: [.posixPermissions: 0o700])
        // Set permissions on the temporary inode before it becomes visible at the destination.
        let temp = url.deletingLastPathComponent().appendingPathComponent(".ccs-\(UUID().uuidString)")
        guard FileManager.default.createFile(atPath: temp.path, contents: data, attributes: [.posixPermissions: 0o600]) else { throw AccountError.message("Cannot write account data.") }
        defer { try? FileManager.default.removeItem(at: temp) }
        guard rename(temp.path, url.path) == 0 else { throw AccountError.message("Cannot replace account data (\(errno)).") }
    }
    func load() throws -> [SavedAccount] {
        let file = root.appendingPathComponent("accounts.json")
        guard FileManager.default.fileExists(atPath: file.path) else { return [] }
        return try JSONDecoder().decode([SavedAccount].self, from: Data(contentsOf: file))
    }
    func save(_ accounts: [SavedAccount]) throws { try secureWrite(JSONEncoder().encode(accounts), to: root.appendingPathComponent("accounts.json")) }
    func secret(_ account: SavedAccount) throws -> AccountSecret {
        guard let data = try vault.read(service, account.id) ?? vault.read(legacyService, account.id) else { throw AccountError.message("Saved credentials are missing. Sign in again.") }
        return try JSONDecoder().decode(AccountSecret.self, from: data)
    }
    func jwt(_ value: String?) -> [String: Any] {
        guard let part = value?.split(separator: ".").dropFirst().first else { return [:] }
        var base = String(part).replacingOccurrences(of: "-", with: "+").replacingOccurrences(of: "_", with: "/")
        base += String(repeating: "=", count: (4 - base.count % 4) % 4)
        guard let data = Data(base64Encoded: base) else { return [:] }
        return (try? object(data)) ?? [:]
    }
    func identity(_ secret: AccountSecret, provider: AccountProvider) throws -> (String, String) {
        let auth = try object(secret.credentials)
        if provider == .codex {
            guard let tokens = auth["tokens"] as? [String: Any], let access = tokens["access_token"] as? String, !access.isEmpty else { throw AccountError.message("Sign in with a ChatGPT account. API-key accounts do not expose subscription usage.") }
            let claims = jwt(tokens["id_token"] as? String)
            let accessClaims = jwt(access)
            let scoped = (claims["https://api.openai.com/auth"] as? [String: Any]) ?? [:]
            guard let account = tokens["account_id"] as? String ?? scoped["chatgpt_account_id"] as? String,
                  let subject = claims["sub"] as? String ?? accessClaims["sub"] as? String else { throw AccountError.message("Cannot identify this Codex account. Sign in again.") }
            return ("\(subject):\(account)", claims["email"] as? String ?? "Codex · \(account.prefix(8))")
        }
        guard let oauth = auth["claudeAiOauth"] as? [String: Any], let token = oauth["accessToken"] as? String, !token.isEmpty else { throw AccountError.message("Claude subscription credentials were not found. Run claude auth login first.") }
        let profile = try secret.profile.map(object) ?? [:]
        guard let uuid = profile["accountUuid"] as? String ?? profile["emailAddress"] as? String else { throw AccountError.message("Claude account identity is missing. Complete sign-in and retry.") }
        let org = profile["organizationUuid"] as? String ?? ""
        return ("\(uuid):\(org)", profile["emailAddress"] as? String ?? "Claude · \(uuid.prefix(8))")
    }
    func claudeService(directory: URL?) -> String {
        guard let directory else { return "Claude Code-credentials" }
        let path = directory.resolvingSymlinksInPath().path.precomposedStringWithCanonicalMapping
        let hash = SHA256.hash(data: Data(path.utf8)).map { String(format: "%02x", $0) }.joined()
        return "Claude Code-credentials-\(hash.prefix(8))"
    }
    func currentClaudeIdentity() -> String? {
        let profileURL = home.appendingPathComponent(".claude.json")
        guard let data = try? Data(contentsOf: profileURL),
              let config = try? object(data),
              let profile = config["oauthAccount"] as? [String: Any],
              let uuid = profile["accountUuid"] as? String ?? profile["emailAddress"] as? String else { return nil }
        let org = profile["organizationUuid"] as? String ?? ""
        return "\(uuid):\(org)"
    }
    func capture(_ provider: AccountProvider, directory: URL? = nil) throws -> AccountSecret? {
        if provider == .codex {
            let dir = directory ?? home.appendingPathComponent(".codex")
            let config = (try? String(contentsOf: dir.appendingPathComponent("config.toml"), encoding: .utf8)) ?? ""
            if directory == nil && config.range(of: #"(?m)^\s*cli_auth_credentials_store\s*=\s*["'](?:keyring|auto)["']"#, options: .regularExpression) != nil {
                throw AccountError.message("Codex uses Keychain authentication. Set cli_auth_credentials_store = \"file\" in ~/.codex/config.toml and sign in before importing or switching.")
            }
            let file = dir.appendingPathComponent("auth.json")
            guard FileManager.default.fileExists(atPath: file.path) else { return nil }
            return AccountSecret(credentials: try Data(contentsOf: file))
        }
        let dir = directory ?? home.appendingPathComponent(".claude")
        let credentials = try vault.read(claudeService(directory: directory), user)
        let fallback = dir.appendingPathComponent(".credentials.json")
        guard let data = try credentials ?? (FileManager.default.fileExists(atPath: fallback.path) ? Data(contentsOf: fallback) : nil) else { return nil }
        let profileURL = directory == nil ? home.appendingPathComponent(".claude.json") : dir.appendingPathComponent(".claude.json")
        let config = try object(Data(contentsOf: profileURL))
        return AccountSecret(credentials: data, profile: try (config["oauthAccount"] as? [String: Any]).map(encode))
    }
    @discardableResult func store(_ secret: AccountSecret, provider: AccountProvider, accounts: inout [SavedAccount]) throws -> SavedAccount {
        let (identity, name) = try identity(secret, provider: provider)
        let account = accounts.first { $0.provider == provider && $0.identity == identity } ?? SavedAccount(id: UUID().uuidString, provider: provider, identity: identity, name: name)
        var toSave = secret
        if provider == .claude, let existing = try? self.secret(account),
           let incomingOAuth = try object(secret.credentials)["claudeAiOauth"] as? [String: Any],
           let savedOAuth = try object(existing.credentials)["claudeAiOauth"] as? [String: Any],
           let incomingExpiry = (incomingOAuth["expiresAt"] as? NSNumber)?.doubleValue,
           let savedExpiry = (savedOAuth["expiresAt"] as? NSNumber)?.doubleValue,
           savedExpiry > incomingExpiry {
            toSave = existing
        }
        try vault.write(JSONEncoder().encode(toSave), service, account.id)
        if !accounts.contains(where: { $0.id == account.id }) { accounts.append(account) }
        try save(accounts)
        return account
    }
    func activate(_ account: SavedAccount, accounts: inout [SavedAccount]) throws {
        let target = try secret(account)
        guard try identity(target, provider: account.provider).0 == account.identity else { throw AccountError.message("Account identity mismatch. Sign in again.") }
        // Save the outgoing account, including rotated tokens, before replacing anything.
        if let current = try capture(account.provider) {
            let sameAccount = try identity(current, provider: account.provider).0 == account.identity
            if account.provider != .codex || !sameAccount {
                try store(current, provider: account.provider, accounts: &accounts)
            } else {
                let currentRefresh = try object(current.credentials)["last_refresh"] as? String ?? ""
                let savedRefresh = try object(target.credentials)["last_refresh"] as? String ?? ""
                if currentRefresh >= savedRefresh {
                    try store(current, provider: account.provider, accounts: &accounts)
                }
            }
        }
        // The outgoing account may also be the target. In that case store()
        // just updated its token, so read it again before writing credentials.
        let latest = try secret(account)
        if account.provider == .codex {
            try secureWrite(latest.credentials, to: home.appendingPathComponent(".codex/auth.json"))
        } else {
            let profileURL = home.appendingPathComponent(".claude.json")
            let oldProfile = try? Data(contentsOf: profileURL)
            var config = try oldProfile.map(object) ?? [:]
            config["oauthAccount"] = try latest.profile.map(object)
            let old = try vault.read(claudeService(directory: nil), user)
            let fallback = home.appendingPathComponent(".claude/.credentials.json")
            let oldFallback = FileManager.default.fileExists(atPath: fallback.path) ? try Data(contentsOf: fallback) : nil
            try vault.write(latest.credentials, claudeService(directory: nil), user)
            do {
                if oldFallback != nil { try secureWrite(latest.credentials, to: fallback) }
                try secureWrite(encode(config), to: profileURL)
            } catch {
                do {
                    if let old { try vault.write(old, claudeService(directory: nil), user) }
                    else { try vault.remove(claudeService(directory: nil), user) }
                    if let oldFallback { try secureWrite(oldFallback, to: fallback) }
                } catch { throw AccountError.message("Switch failed and rollback failed. Saved accounts are intact; sign in again before continuing.") }
                throw error
            }
        }
    }
    func importLegacyDesktopCredentials(_ account: SavedAccount) throws {
        guard account.provider == .codex, UUID(uuidString: account.id) != nil else { return }
        let file = root.appendingPathComponent("desktop/\(account.id)/codex/auth.json")
        guard FileManager.default.fileExists(atPath: file.path) else { return }
        let candidate = AccountSecret(credentials: try Data(contentsOf: file))
        guard try identity(candidate, provider: .codex).0 == account.identity else { return }
        let saved = try secret(account)
        let candidateRefresh = try object(candidate.credentials)["last_refresh"] as? String ?? ""
        let savedRefresh = try object(saved.credentials)["last_refresh"] as? String ?? ""
        if candidateRefresh > savedRefresh {
            try vault.write(JSONEncoder().encode(candidate), service, account.id)
        }
    }
    static func parseUsage(_ json: [String: Any], provider: AccountProvider) -> [UsageWindow] {
        let container = provider == .codex ? (json["rate_limit"] as? [String: Any] ?? [:]) : json
        let keys = provider == .codex ? ["primary_window", "secondary_window"] : ["five_hour", "seven_day"]
        return keys.enumerated().compactMap { index, key in
            guard let value = container[key] as? [String: Any], let used = (value[provider == .codex ? "used_percent" : "utilization"] as? NSNumber)?.doubleValue, used.isFinite else { return nil }
            let reset: Date?
            if let seconds = value["reset_at"] as? Double { reset = Date(timeIntervalSince1970: seconds) }
            else if let text = value["resets_at"] as? String {
                let formatter = ISO8601DateFormatter(); formatter.formatOptions.insert(.withFractionalSeconds)
                reset = formatter.date(from: text) ?? ISO8601DateFormatter().date(from: text)
            } else { reset = nil }
            let seconds = (value["limit_window_seconds"] as? Int) ?? (index == 0 ? 18000 : 604800)
            let label = seconds == 18000 ? "5 hours" : seconds == 604800 ? "Weekly" : "\(seconds / 3600) hours"
            return UsageWindow(label: label, used: min(100, max(0, used)), reset: reset)
        }
    }
    func refreshClaudeToken(_ account: SavedAccount, staleAccess: String, session: URLSession) async throws -> String {
        var saved = try secret(account)
        var auth = try object(saved.credentials)
        guard var oauth = auth["claudeAiOauth"] as? [String: Any],
              let refresh = oauth["refreshToken"] as? String, !refresh.isEmpty else {
            throw AccountError.message("Claude sign-in expired. Sign in again to load usage.")
        }
        // Claude Code uses this OAuth client and JSON token exchange for its own refresh.
        var request = URLRequest(url: URL(string: "https://console.anthropic.com/v1/oauth/token")!)
        request.httpMethod = "POST"
        request.timeoutInterval = 15
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.httpBody = try encode([
            "grant_type": "refresh_token",
            "refresh_token": refresh,
            "client_id": "9d1c250a-e61b-44d9-88ed-5944d1962f5e"
        ])
        let (data, response) = try await session.data(for: request)
        let code = (response as? HTTPURLResponse)?.statusCode ?? 0
        guard code == 200,
              let result = try? object(data),
              let access = result["access_token"] as? String, !access.isEmpty,
              let lifetime = (result["expires_in"] as? NSNumber)?.doubleValue, lifetime > 0 else {
            throw AccountError.message(code == 400 || code == 401 || code == 403
                ? "Claude sign-in expired. Sign in again to load usage."
                : "Could not refresh Claude sign-in (HTTP \(code)). Retry later.")
        }
        oauth["accessToken"] = access
        oauth["refreshToken"] = result["refresh_token"] as? String ?? refresh
        oauth["expiresAt"] = (Date().timeIntervalSince1970 + lifetime) * 1000
        auth["claudeAiOauth"] = oauth
        saved.credentials = try encode(auth)
        guard try identity(saved, provider: .claude).0 == account.identity else {
            throw AccountError.message("Claude account identity changed. Sign in again.")
        }
        // Persist rotated refresh tokens before retrying usage. A passive usage
        // refresh must not request access to Claude Code's Keychain item.
        try vault.write(JSONEncoder().encode(saved), service, account.id)
        let fallback = home.appendingPathComponent(".claude/.credentials.json")
        if currentClaudeIdentity() == account.identity,
           let current = try? object(Data(contentsOf: fallback)),
           let currentOAuth = current["claudeAiOauth"] as? [String: Any],
           currentOAuth["accessToken"] as? String == staleAccess {
            try secureWrite(saved.credentials, to: fallback)
        }
        return access
    }
    func usage(_ account: SavedAccount, session: URLSession = .shared) async throws -> AccountUsage {
        let auth = try object(secret(account).credentials)
        let codex = account.provider == .codex
        let tokens = auth[codex ? "tokens" : "claudeAiOauth"] as? [String: Any] ?? [:]
        guard let access = tokens[codex ? "access_token" : "accessToken"] as? String else { throw AccountError.message("Sign in again to load usage.") }
        var request = URLRequest(url: URL(string: codex ? "https://chatgpt.com/backend-api/wham/usage" : "https://api.anthropic.com/api/oauth/usage")!)
        request.timeoutInterval = 15
        request.setValue("Bearer \(access)", forHTTPHeaderField: "Authorization")
        if codex {
            request.setValue(tokens["account_id"] as? String, forHTTPHeaderField: "ChatGPT-Account-Id")
            request.setValue("codex-cli", forHTTPHeaderField: "User-Agent")
            request.setValue("codex-1", forHTTPHeaderField: "OpenAI-Beta")
        } else {
            request.setValue("oauth-2025-04-20", forHTTPHeaderField: "anthropic-beta")
            request.setValue("claude-code/2.1.0", forHTTPHeaderField: "User-Agent")
        }
        var (data, response) = try await session.data(for: request)
        var code = (response as? HTTPURLResponse)?.statusCode ?? 0
        if !codex && code == 401 {
            let refreshed = try await refreshClaudeToken(account, staleAccess: access, session: session)
            request.setValue("Bearer \(refreshed)", forHTTPHeaderField: "Authorization")
            (data, response) = try await session.data(for: request)
            code = (response as? HTTPURLResponse)?.statusCode ?? 0
        }
        if code == 429 { throw AccountError.rateLimited }
        guard code == 200 else { throw AccountError.message(code == 401 || code == 403 ? "Sign in again to refresh usage." : "Usage unavailable (HTTP \(code)). Retry later.") }
        let windows = Self.parseUsage(try object(data), provider: account.provider)
        guard !windows.isEmpty else { throw AccountError.message("Usage limits are not available for this account.") }
        return AccountUsage(windows: windows, updated: Date())
    }
}

@MainActor final class AccountsModel: ObservableObject {
    @Published var accounts: [SavedAccount] = []
    @Published var active: [AccountProvider: String] = [:]
    @Published var usage: [String: AccountUsage] = [:]
    @Published var message = ""
    @Published var refreshing = false
    @Published var loadingUsage: Set<String> = []
    @Published var signingIn: AccountProvider?
    @Published var switchingCodex = false
    @Published var switchingClaude = false
    let repository: AccountRepository
    private var loginTask: Task<Void, Never>?
    private var nextAutomaticUsageRequest: [String: Date] = [:]
    private var rateLimitedUntil: [String: Date] = [:]
    init(repository: AccountRepository = AccountRepository()) {
        self.repository = repository
        do { accounts = try repository.load() } catch { message = "Cannot load saved accounts: \(error.localizedDescription)" }
    }
    func syncActive() throws {
        for provider in AccountProvider.allCases {
            if let current = try repository.capture(provider) {
                let identity = try repository.identity(current, provider: provider).0
                if let saved = accounts.first(where: { $0.provider == provider && $0.identity == identity }) {
                    try repository.store(current, provider: provider, accounts: &accounts)
                    active[provider] = saved.id
                } else { active[provider] = nil }
            } else { active[provider] = nil }
        }
    }
    func importCurrent(_ provider: AccountProvider, refreshUsage: Bool = true) {
        importCapturedCurrent(provider, refreshUsage: refreshUsage)
    }
    private func importCapturedCurrent(_ provider: AccountProvider, refreshUsage: Bool = true) {
        do {
            guard let secret = try repository.capture(provider) else {
                if provider == .claude { signInCurrentClaude(); return }
                throw AccountError.message("No \(provider.rawValue) login found. Use Add account to sign in.")
            }
            let account = try repository.store(secret, provider: provider, accounts: &accounts)
            active[provider] = account.id
            message = "Imported \(account.name)."
            if refreshUsage { refresh() }
        } catch { message = error.localizedDescription }
    }
    private func signInCurrentClaude() {
        guard signingIn == nil else { return }
        do {
            let directory = repository.root.appendingPathComponent("login-current-\(UUID().uuidString)")
            try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true, attributes: [.posixPermissions: 0o700])
            func quote(_ string: String) -> String { "'" + string.replacingOccurrences(of: "'", with: "'\\''") + "'" }
            let script = directory.appendingPathComponent("sign-in.command")
            let text = "#!/bin/zsh -l\nunset ANTHROPIC_API_KEY ANTHROPIC_AUTH_TOKEN CLAUDE_CODE_OAUTH_TOKEN CLAUDE_CONFIG_DIR\nclaude auth login\nresult=$?\nif [ $result -eq 0 ]; then touch \(quote(directory.appendingPathComponent("complete").path)); else touch \(quote(directory.appendingPathComponent("failed").path)); fi\nexit $result\n"
            try repository.secureWrite(Data(text.utf8), to: script)
            try FileManager.default.setAttributes([.posixPermissions: 0o700], ofItemAtPath: script.path)
            guard NSWorkspace.shared.open(script) else { throw AccountError.message("Could not open Terminal for Claude sign-in.") }
            signingIn = .claude
            message = "Claude Code is signed out. Complete claude auth login in Terminal and your browser; ccs will import it automatically."
            loginTask = Task {
                defer {
                    try? FileManager.default.removeItem(at: directory)
                    signingIn = nil
                }
                for _ in 0..<300 {
                    do { try await Task.sleep(for: .seconds(2)) } catch { return }
                    if FileManager.default.fileExists(atPath: directory.appendingPathComponent("failed").path) {
                        message = "Claude sign-in failed. Run claude auth login in Terminal and retry Import current."; return
                    }
                    if FileManager.default.fileExists(atPath: directory.appendingPathComponent("complete").path) {
                        importCapturedCurrent(.claude)
                        return
                    }
                }
                message = "Claude sign-in timed out. Run claude auth login in Terminal and retry Import current."
            }
        } catch { message = error.localizedDescription }
    }
    func activate(_ account: SavedAccount, refreshUsage: Bool = true) {
        do {
            if account.provider == .codex {
                guard !switchingCodex else { return }
                guard let app = NSWorkspace.shared.urlForApplication(withBundleIdentifier: "com.openai.codex") else {
                    throw AccountError.message("Codex Desktop is not installed.")
                }
                // Stop the app server before replacing auth.json; otherwise its cached
                // credentials can keep the visible Desktop on the previous account.
                let running = NSWorkspace.shared.runningApplications.filter { $0.bundleIdentifier == "com.openai.codex" }
                let sharedHome = repository.home
                switchingCodex = true
                message = "Switching Codex Desktop to \(account.name)…"
                Task {
                    defer { switchingCodex = false }
                    var stopped = false
                    do {
                        try await Task.detached { try CodexDesktopLauncher.stop(running) }.value
                        stopped = true
                        for saved in accounts where saved.provider == .codex {
                            try repository.importLegacyDesktopCredentials(saved)
                        }
                        try repository.activate(account, accounts: &accounts)
                        active[.codex] = account.id
                        try await Task.detached { try CodexDesktopLauncher.launch(app: app, home: sharedHome) }.value
                        message = "Codex CLI and Desktop switched to \(account.name)."
                        if refreshUsage { refresh() }
                    } catch {
                        // A failed credential swap must not strand the user with Desktop closed.
                        if stopped {
                            try? await Task.detached { try CodexDesktopLauncher.launch(app: app, home: sharedHome) }.value
                        }
                        message = error.localizedDescription
                    }
                }
            } else {
                guard !switchingClaude else { return }
                guard let app = NSWorkspace.shared.urlForApplication(withBundleIdentifier: "com.anthropic.claudefordesktop") else {
                    try repository.activate(account, accounts: &accounts)
                    active[.claude] = account.id
                    message = "Claude Code switched to \(account.name)."
                    if refreshUsage { refresh() }
                    return
                }
                let saved = try repository.secret(account)
                guard try repository.identity(saved, provider: .claude).0 == account.identity else {
                    throw AccountError.message("Account identity mismatch. Sign in again.")
                }
                let running = NSWorkspace.shared.runningApplications.filter { $0.bundleIdentifier == "com.anthropic.claudefordesktop" }
                let profiles = ClaudeDesktopProfiles(repository: repository)
                let previous = accounts.first { $0.id == profiles.currentSlot(accounts: accounts) }
                switchingClaude = true
                message = "Switching Claude Desktop to \(account.name)…"
                Task {
                    defer { switchingClaude = false }
                    var stopped = false
                    var changedProfile = false
                    do {
                        try await Task.detached { try ClaudeDesktopLauncher.stop(running) }.value
                        stopped = true
                        let targetAlreadySelected = profiles.currentSlot(accounts: accounts) == account.id
                        let signedIn = try profiles.select(account, accounts: accounts)
                        changedProfile = !targetAlreadySelected
                        do {
                            try repository.activate(account, accounts: &accounts)
                        } catch {
                            if changedProfile, let previous {
                                _ = try? profiles.select(previous, accounts: accounts)
                            }
                            throw error
                        }
                        active[.claude] = account.id
                        try await Task.detached { try ClaudeDesktopLauncher.launch(app: app) }.value
                        message = signedIn
                            ? "Claude Code and Desktop switched to \(account.name)."
                            : "Claude Code switched to \(account.name). Sign in to this account in Claude Desktop once; ccs will keep that login for future switches."
                        if refreshUsage { refresh() }
                    } catch {
                        if stopped { try? await Task.detached { try ClaudeDesktopLauncher.launch(app: app) }.value }
                        message = error.localizedDescription
                    }
                }
            }
        } catch { message = error.localizedDescription }
    }
    func remove(_ account: SavedAccount) {
        do {
            let remaining = accounts.filter { $0.id != account.id }
            try repository.save(remaining)
            try repository.vault.remove(repository.service, account.id)
            try repository.vault.remove(repository.legacyService, account.id)
            accounts = remaining; usage[account.id] = nil
            if active[account.provider] == account.id { active[account.provider] = nil }
            message = "Removed saved account. The CLI remains signed in."
        } catch { message = error.localizedDescription }
    }
    func refresh(forceUsage: Bool = false) {
        guard !refreshing else { return }
        refreshing = true
        loadingUsage = Set(accounts.map(\.id))
        Task {
            defer {
                loadingUsage.removeAll()
                refreshing = false
            }
            // A missing login for one provider must not hide the other provider's usage.
            for provider in AccountProvider.allCases where accounts.contains(where: { $0.provider == provider }) {
                if provider == .claude {
                    let identity = repository.currentClaudeIdentity()
                    active[provider] = accounts.first(where: { $0.provider == provider && $0.identity == identity })?.id
                    continue
                }
                do {
                    if let current = try repository.capture(provider) {
                        let identity = try repository.identity(current, provider: provider).0
                        if let saved = accounts.first(where: { $0.provider == provider && $0.identity == identity }) {
                            try repository.store(current, provider: provider, accounts: &accounts)
                            active[provider] = saved.id
                        } else { active[provider] = nil }
                    } else { active[provider] = nil }
                } catch { active[provider] = nil }
            }
            for account in accounts {
                let now = Date()
                if account.provider == .claude && !forceUsage {
                    guard now >= (rateLimitedUntil[account.id] ?? .distantPast) else {
                        loadingUsage.remove(account.id)
                        continue
                    }
                    guard now >= (nextAutomaticUsageRequest[account.id] ?? .distantPast) else {
                        loadingUsage.remove(account.id)
                        continue
                    }
                    nextAutomaticUsageRequest[account.id] = now.addingTimeInterval(10 * 60)
                }
                do {
                    usage[account.id] = try await repository.usage(account)
                    rateLimitedUntil[account.id] = nil
                }
                catch {
                    if let accountError = error as? AccountError, case .rateLimited = accountError {
                        rateLimitedUntil[account.id] = Date().addingTimeInterval(15 * 60)
                    }
                    var old = usage[account.id] ?? AccountUsage()
                    old.error = error.localizedDescription; usage[account.id] = old
                }
                loadingUsage.remove(account.id)
            }
        }
    }
    func add(_ provider: AccountProvider) {
        guard signingIn == nil else { return }
        do {
            let directory = repository.root.appendingPathComponent("login-\(UUID().uuidString)")
            try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true, attributes: [.posixPermissions: 0o700])
            if provider == .codex { try repository.secureWrite(Data("cli_auth_credentials_store = \"file\"\n".utf8), to: directory.appendingPathComponent("config.toml")) }
            func quote(_ string: String) -> String { "'" + string.replacingOccurrences(of: "'", with: "'\\''") + "'" }
            let script = directory.appendingPathComponent("sign-in.command")
            let env = provider == .codex ? "CODEX_HOME" : "CLAUDE_CONFIG_DIR"
            let command = provider == .codex ? "codex login" : "claude auth login"
            let text = "#!/bin/zsh -l\nunset OPENAI_API_KEY ANTHROPIC_API_KEY ANTHROPIC_AUTH_TOKEN CLAUDE_CODE_OAUTH_TOKEN\nexport \(env)=\(quote(directory.path))\n\(command)\nresult=$?\nif [ $result -eq 0 ]; then touch \(quote(directory.appendingPathComponent("complete").path)); else touch \(quote(directory.appendingPathComponent("failed").path)); fi\nexit $result\n"
            try repository.secureWrite(Data(text.utf8), to: script)
            try FileManager.default.setAttributes([.posixPermissions: 0o700], ofItemAtPath: script.path)
            guard NSWorkspace.shared.open(script) else { throw AccountError.message("Could not open Terminal for sign-in.") }
            signingIn = provider; message = "Complete \(provider.rawValue) sign-in in Terminal and your browser. Your current account stays active."
            loginTask = Task {
                defer {
                    try? repository.vault.remove(repository.claudeService(directory: directory), repository.user)
                    try? FileManager.default.removeItem(at: directory)
                    signingIn = nil
                }
                for _ in 0..<300 {
                    do { try await Task.sleep(for: .seconds(2)) } catch { return }
                    if FileManager.default.fileExists(atPath: directory.appendingPathComponent("failed").path) {
                        message = "Sign-in failed. Check Terminal, verify the CLI is installed, and retry."; return
                    }
                    if FileManager.default.fileExists(atPath: directory.appendingPathComponent("complete").path) {
                        do {
                            guard let secret = try repository.capture(provider, directory: directory) else { throw AccountError.message("Sign-in finished without credentials.") }
                            let account = try repository.store(secret, provider: provider, accounts: &accounts)
                            message = "Added \(account.name). Click Switch to use it."
                            refresh()
                        } catch { message = error.localizedDescription }
                        return
                    }
                }
                message = "Sign-in timed out. Close the sign-in Terminal and retry."
            }
        } catch { message = error.localizedDescription }
    }
}

struct AccountsView: View {
    @ObservedObject var model: AccountsModel
    @State private var removing: SavedAccount?
    var body: some View {
        VStack(alignment: .leading, spacing: 14) {
            HStack {
                Text("Accounts").font(.system(size: 18, weight: .semibold))
                Spacer()
                if model.refreshing { ProgressView().controlSize(.small) }
                Button { model.refresh() } label: { Image(systemName: "arrow.clockwise") }.disabled(model.refreshing)
            }
            Text("Switch Codex CLI and Desktop with shared session history. Claude switches Code and Desktop; sign in to each Claude Desktop account once.")
                .font(.system(size: 11)).foregroundStyle(.secondary)
            ScrollView {
                VStack(alignment: .leading, spacing: 16) {
                    ForEach(AccountProvider.allCases) { provider in
                        VStack(alignment: .leading, spacing: 8) {
                            HStack {
                                Text(provider.rawValue).font(.system(size: 12, weight: .semibold))
                                Spacer()
                                Button("Import current") { model.importCurrent(provider) }
                                Button("＋ Add account") { model.add(provider) }.disabled(model.signingIn != nil)
                            }
                            ForEach(model.accounts.filter { $0.provider == provider }) { account in
                                VStack(alignment: .leading, spacing: 9) {
                                    HStack {
                                        Text(account.name).font(.system(size: 12, weight: .medium)).lineLimit(1)
                                        Spacer()
                                        if model.active[provider] == account.id {
                                            Label("Active", systemImage: "checkmark.circle.fill").foregroundStyle(.green)
                                            Button("Restart Desktop") { model.activate(account) }.disabled(model.switchingCodex || model.switchingClaude)
                                        } else {
                                            Button("Switch") { model.activate(account) }.disabled(model.switchingCodex || model.switchingClaude)
                                        }
                                        Button { removing = account } label: { Image(systemName: "trash") }.buttonStyle(.plain).foregroundStyle(.secondary)
                                    }
                                    if model.loadingUsage.contains(account.id) && model.usage[account.id] == nil {
                                        ProgressView("Loading usage…").controlSize(.small)
                                    } else if let usage = model.usage[account.id] {
                                        if model.loadingUsage.contains(account.id) { ProgressView().controlSize(.small) }
                                        ForEach(usage.windows) { window in
                                            HStack(spacing: 10) {
                                                Text(window.label).frame(width: 48, alignment: .leading)
                                                ProgressView(value: window.used, total: 100).tint(window.used >= 90 ? .orange : .accentColor).frame(width: 110)
                                                Text("\(Int(window.used))% used").monospacedDigit()
                                                Spacer()
                                                if let reset = window.reset { Text("Resets \(reset, style: .relative)").foregroundStyle(.secondary) }
                                            }
                                        }
                                        if let error = usage.error { Text(error).foregroundStyle(.orange) }
                                        if let updated = usage.updated { Text("Updated \(updated, style: .relative) ago\(usage.error == nil ? "" : " · Stale")").foregroundStyle(.secondary) }
                                    } else { Text("Usage not loaded").foregroundStyle(.secondary) }
                                }
                                .padding(12).background(.white.opacity(0.045), in: RoundedRectangle(cornerRadius: 8))
                            }
                            if !model.accounts.contains(where: { $0.provider == provider }) {
                                Text("No saved accounts. Import the current login or add another account.").foregroundStyle(.secondary).padding(.vertical, 8)
                            }
                        }
                    }
                }
            }
            if model.signingIn != nil { ProgressView("Waiting for sign-in…").controlSize(.small) }
            if !model.message.isEmpty { Text(model.message).foregroundStyle(.secondary).fixedSize(horizontal: false, vertical: true) }
        }
        .font(.system(size: 11)).padding(22)
        .onAppear { model.refresh() }
        .task { while !Task.isCancelled { do { try await Task.sleep(for: .seconds(60)) } catch { return }; model.refresh() } }
        .alert("Remove saved account?", isPresented: Binding(get: { removing != nil }, set: { if !$0 { removing = nil } })) {
            Button("Cancel", role: .cancel) { removing = nil }
            Button("Remove", role: .destructive) { if let removing { model.remove(removing) }; removing = nil }
        } message: { Text("This removes the saved credentials from ccs. It does not sign the CLI out.") }
    }
}
